services:
  openproject:
    image: openproject/openproject:15
    container_name: openproject
    restart: always
    volumes:
      - ./pgdata:/var/openproject/pgdata
      - ./assets:/var/openproject/assets
    networks:
      - frontend
    labels:
      - "traefik.enable=true" 
      - "traefik.docker.network=frontend"
      - "traefik.http.routers.test_machine.tls.certresolver=myresolver"
      - "traefik.http.services.test_machine.loadbalancer.server.port=80"
      - "traefik.http.routers.test_machine.rule=Host(`$OPENPROJECT_HOST__NAME`)"


networks:
  frontend:
    external: true